### ISSUE TITLE
Username 'jamesharrison92' is failing in the FacebookFeed block

### ISSUE THREAD

**Issue by hansmosh** [nio-blocks/facebook#30]
This query string 'jamesharrison92' is causing an error and the block attempts to retry until it runs out of retries. I think this block should skip the query instead of retry when this message comes back from facebook.

[2015-01-15 21:48:28.883] NIO [ERROR] [source_facebook.facebook_flagged] Polling request of https://graph.facebook.com/v2.2/jamesharrison92/posts?since=1421350985&limit=10&access_token=***** returned status 404: {'error': {'message': '(#803) Cannot query users by their username (jamesharrison92)', 'code': 803, 'type': 'OAuthException'}}

**Comment by oleiman** [comment]
http://stackoverflow.com/questions/25258670/facebook-graph-api-v2-1-getting-user-id-and-his-posts

Looks like this isn't even possible in the v2 API...did this ever work? Was it v1 before?

**Comment by hansmosh** [comment]
You're right. It never works for users. This block does work for other pages that aren't users. (ex. groups, apps, etc..). This block is meant for those and should not break if someone accidentally puts in a user name. They look reallllly similar on facebook so it's a pretty easy user error to make.

For example, I'm a user:
https://www.facebook.com/cbrackert

But this is a page:
https://www.facebook.com/TomBrady

cbrackert would error in this block. TomBrady would work.

**Comment by oleiman** [comment]
So, probably we just look for that error and print a warning like "Hey
jackass, no usernames". Work for you?

**Comment by hansmosh** [comment]
Haha, yeah. Something like that. Except in most cases with nioMedia, the person entering the terms is not the person looking at the logs, so the wrong person is being called names.

The instagram user block does something similar when you try to query a private user. This message should be like that one.

**Comment by oleiman** [comment]
Noted. I'll probably just include the error message in the log message.
